### ISSUE TITLE
Adding support to additional features, such as buff timners?

### ISSUE THREAD

**Issue by Adephx** [misterokaygo/MapAssist#142]
https://github.com/panthernet/D2RSO

Is there any interest from the authors for adding additional features, such as buff timers? Were you able to find the opcode packet that handles skills interaction with the server? If so, we don't have to rely on the method above?

**Comment by AudriusButkevicius** [comment]
We don't parse packets etc, but I think its better for these applications to remain separate, hence closing.

**Comment by Adephx** [comment]
> We don't parse packets etc, but I think its better for these applications to remain separate, hence closing.

How are we reading the map seeds then and why did why do we rely on offsets?

**Comment by AudriusButkevicius** [comment]
The code is all out on github, so feel free to explore how it works.

**Comment by Adephx** [comment]
Cheers, I haven't thought about it. Digging through 20k lines of code on a slim chance of compatibility is certainly easier and faster than getting a clear answer. I can see it from your tone, that is much better for me just to fork the whole thing and work on it on my own, because you clearly don't want a conversation.
