### ISSUE TITLE
windows 11 how to get this working?

### ISSUE THREAD

**Issue by dawoat** [misterokaygo/MapAssist#144]
Hello,

I have downloaded it. Build it with visual studio.
Dev branch generates an error on start.
Main Branch -> Rebuild all and start. The only thing i see is the icon in the taskbar.
No overlay. Whats wrong here? Using Win 11 and Vs2019.

Is there something else to config?

**Comment by vtscarlos** [comment]
Build development branch, works for me on windows 11

**Comment by paradoxial** [comment]
This is working on Windows 11 x64. Tested in VMs.

**Comment by misterokaygo** [comment]
try this latest build https://github.com/misterokaygo/MapAssist/releases/tag/latest
