### ISSUE TITLE
Not working today

### ISSUE THREAD

**Issue by micgogo** [misterokaygo/MapAssist#153]
The map assist stopped working today, there are no data pared to the map api, i have tried both develop and latest version same issue

**Comment by brunoavelar** [comment]
The issue is in the address of the act. Always falling in the exception. 
`var act = Read<Act>(processHandle, (IntPtr)PlayerUnit.pAct);
                var mapSeed = act.MapSeed;

                if (mapSeed <= 0 || mapSeed > 0xFFFFFFFF)
                {
                    throw new Exception("Map seed is out of bounds.");
                }`

**Comment by misterokaygo** [comment]
https://github.com/misterokaygo/MapAssist/releases/tag/latest try this newest build
