### ISSUE TITLE
latest & develop version fail to launch 

### ISSUE THREAD

**Issue by dan333dan** [misterokaygo/MapAssist#157]
Anyone can advise how to fix the error below?

************** Exception Text **************
System.TypeInitializationException: 'MapAssist.Settings.Map' 的類型初始設定式發生例外狀況。 ---> System.ArgumentNullException: 值不能為 null。
參數名稱: value
   於 System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureParameter)
   於 System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   於 System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   於 MapAssist.Settings.Map..cctor()
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 MapAssist.Settings.Map.LookupMapColor(Int32 type)
   於 MapAssist.Settings.Map.InitMapColors()
   於 MapAssist.Overlay.Overlay_Load(Object sender, EventArgs e)
   於 System.Windows.Forms.Form.OnLoad(EventArgs e)
   於 System.Windows.Forms.Form.OnCreateControl()
   於 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   於 System.Windows.Forms.Control.CreateControl()
   於 System.Windows.Forms.Control.WmShowWindow(Message& m)
   於 System.Windows.Forms.Control.WndProc(Message& m)
   於 System.Windows.Forms.Form.WmShowWindow(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![error](https://user-images.githubusercontent.com/94340555/141723851-36b112a7-56b8-4720-b7a9-ac7c6098fd71.JPG)

**Comment by SilasMueller** [comment]
Can you provide the content of your .config file?

**Comment by dan333dan** [comment]
> Can you provide the content of your .config file?

<?xml version="1.0" encoding="utf-8"?>

<configuration>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a"
                                  culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
            </dependentAssembly>
        </assemblyBinding>
    </runtime>
    <appSettings>
        <add key="ApiEndpoint" value="http://localhost:8080/" />
        <add key="Opacity" value="0.7" />
        <add key="OverlayMode" value="false" />
        <add key="UpdateTime" value="100" />
        <add key="ToggleViaInGameMap" value="true" />
        <add key="AlwaysOnTop" value="true" />
        <add key="Size" value="450" />
        <add key="Rotate" value="true" />
        <add key="MapPosition" value="TopRight" />
        <add key="ToggleKey" value="\" />
        <add key="ClearPrefetchedOnAreaChange" value="false" />
        <add key="PrefetchAreas" value="Catacombs Level 2,Durance Of Hate Level 2" />
        <add key="HiddenAreas" value="Rogue Encampment,Lut Gholein,Kurast Docktown,The Pandemonium Fortress,Harrogath,Forgotten Tower" />

        <add key="Waypoint.IconColor" value="16, 140, 235" />
        <add key="Waypoint.IconShape" value="Rectangle" />
        <add key="Waypoint.IconSize" value="10" />

        <add key="Player.IconColor" value="255, 255, 0" />
        <add key="Player.IconShape" value="Rectangle" />
        <add key="Player.IconSize" value="5" />

        <add key="SuperChest.IconColor" value="17, 255, 0" />
        <add key="SuperChest.IconShape" value="Ellipse" />
        <add key="SuperChest.IconSize" value="10" />

        <add key="NextArea.IconColor" value="237, 107, 0" />
        <add key="NextArea.IconShape" value="Rectangle" />
        <add key="NextArea.IconSize" value="10" />
        <add key="NextArea.LabelColor" value="Chartreuse" />
        <add key="NextArea.LineColor" value="Chartreuse" />
        <add key="NextArea.ArrowHeadSize" value="10" />

        <add key="PreviousArea.IconColor" value="255, 0, 149" />
        <add key="PreviousArea.IconShape" value="Rectangle" />
        <add key="PreviousArea.IconSize" value="10" />
        <add key="PreviousArea.LabelColor" value="Chartreuse" />

        <add key="Quest.LineColor" value="Chartreuse" />
        <add key="Quest.ArrowHeadSize" value="5" />

        <add key="MapColor[0]" value="50, 50, 50" />
        <add key="MapColor[2]" value="10, 51, 23" />
        <add key="MapColor[3]" value="255, 0, 255" />
        <add key="MapColor[4]" value="0, 255, 255" />
        <add key="MapColor[6]" value="80, 51, 33" />
        <add key="MapColor[7]" value="255, 255, 255" />
        <add key="MapColor[16]" value="168, 56, 50" />
        <add key="MapColor[17]" value="255, 51, 255" />
        <add key="MapColor[19]" value="0, 51, 255" />
        <add key="MapColor[20]" value="70, 51, 41" />
        <add key="MapColor[21]" value="255, 0, 255" />
        <add key="MapColor[23]" value="0, 0, 255" />
        <add key="MapColor[33]" value="0, 0, 255" />
        <add key="MapColor[37]" value="50, 51, 23" />
        <add key="MapColor[39]" value="20, 11, 33" />
        <add key="MapColor[53]" value="10, 11, 43" />

        <add key="ClientSettingsProvider.ServiceUri" value="" />
    </appSettings>
    <system.web>
        <membership defaultProvider="ClientAuthenticationMembershipProvider">
            <providers>
                <add name="ClientAuthenticationMembershipProvider"
                     type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                     serviceUri="" />
            </providers>
        </membership>
        <roleManager defaultProvider="ClientRoleProvider" enabled="true">
            <providers>
                <add name="ClientRoleProvider"
                     type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                     serviceUri="" cacheTimeout="86400" />
            </providers>
        </roleManager>
    </system.web>
</configuration>

**Comment by dan333dan** [comment]
> Can you provide the content of your .config file?

<?xml version="1.0" encoding="utf-8"?>

<configuration>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a"
                                  culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
            </dependentAssembly>
        </assemblyBinding>
    </runtime>
    <appSettings>
        <add key="ApiEndpoint" value="http://localhost:8080/" />
        <add key="Opacity" value="0.7" />
        <add key="OverlayMode" value="false" />
        <add key="UpdateTime" value="100" />
        <add key="ToggleViaInGameMap" value="true" />
        <add key="AlwaysOnTop" value="true" />
        <add key="Size" value="450" />
        <add key="Rotate" value="true" />
        <add key="MapPosition" value="TopRight" />
        <add key="ToggleKey" value="\" />
        <add key="ClearPrefetchedOnAreaChange" value="false" />
        <add key="PrefetchAreas" value="Catacombs Level 2,Durance Of Hate Level 2" />
        <add key="HiddenAreas" value="Rogue Encampment,Lut Gholein,Kurast Docktown,The Pandemonium Fortress,Harrogath,Forgotten Tower" />

        <add key="Waypoint.IconColor" value="16, 140, 235" />
        <add key="Waypoint.IconShape" value="Rectangle" />
        <add key="Waypoint.IconSize" value="10" />

        <add key="Player.IconColor" value="255, 255, 0" />
        <add key="Player.IconShape" value="Rectangle" />
        <add key="Player.IconSize" value="5" />

        <add key="SuperChest.IconColor" value="17, 255, 0" />
        <add key="SuperChest.IconShape" value="Ellipse" />
        <add key="SuperChest.IconSize" value="10" />

        <add key="NextArea.IconColor" value="237, 107, 0" />
        <add key="NextArea.IconShape" value="Rectangle" />
        <add key="NextArea.IconSize" value="10" />
        <add key="NextArea.LabelColor" value="Chartreuse" />
        <add key="NextArea.LineColor" value="Chartreuse" />
        <add key="NextArea.ArrowHeadSize" value="10" />

        <add key="PreviousArea.IconColor" value="255, 0, 149" />
        <add key="PreviousArea.IconShape" value="Rectangle" />
        <add key="PreviousArea.IconSize" value="10" />
        <add key="PreviousArea.LabelColor" value="Chartreuse" />

        <add key="Quest.LineColor" value="Chartreuse" />
        <add key="Quest.ArrowHeadSize" value="5" />

        <add key="MapColor[0]" value="50, 50, 50" />
        <add key="MapColor[2]" value="10, 51, 23" />
        <add key="MapColor[3]" value="255, 0, 255" />
        <add key="MapColor[4]" value="0, 255, 255" />
        <add key="MapColor[6]" value="80, 51, 33" />
        <add key="MapColor[7]" value="255, 255, 255" />
        <add key="MapColor[16]" value="168, 56, 50" />
        <add key="MapColor[17]" value="255, 51, 255" />
        <add key="MapColor[19]" value="0, 51, 255" />
        <add key="MapColor[20]" value="70, 51, 41" />
        <add key="MapColor[21]" value="255, 0, 255" />
        <add key="MapColor[23]" value="0, 0, 255" />
        <add key="MapColor[33]" value="0, 0, 255" />
        <add key="MapColor[37]" value="50, 51, 23" />
        <add key="MapColor[39]" value="20, 11, 33" />
        <add key="MapColor[53]" value="10, 11, 43" />

        <add key="ClientSettingsProvider.ServiceUri" value="" />
    </appSettings>
    <system.web>
        <membership defaultProvider="ClientAuthenticationMembershipProvider">
            <providers>
                <add name="ClientAuthenticationMembershipProvider"
                     type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                     serviceUri="" />
            </providers>
        </membership>
        <roleManager defaultProvider="ClientRoleProvider" enabled="true">
            <providers>
                <add name="ClientRoleProvider"
                     type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                     serviceUri="" cacheTimeout="86400" />
            </providers>
        </roleManager>
    </system.web>
</configuration>

**Comment by dan333dan** [comment]
[1115.exe.config.txt](https://github.com/misterokaygo/MapAssist/files/7536692/1115.exe.config.txt)

**Comment by SilasMueller** [comment]
Does the config file in your MapAssist folder also end on .txt?
It should just be .exe.config
Make sure that your file explorer is displaying the file extensions correctly. It is possible to hide them. If they are hidden, a file that ends with .exe.config.txt will be shown as .exe.config

**Comment by dan333dan** [comment]
> Does the config file in your MapAssist folder also end on .txt? It should just be .exe.config Make sure that your file explorer is displaying the file extensions correctly. It is possible to hide them. If they are hidden, a file that ends with .exe.config.txt will be shown as .exe.config

I just change the file format to *.txt so it could be upload the site.

**Comment by SilasMueller** [comment]
It looks like you are using an old config file. Use the .exe.config that comes with the release.

**Comment by dan333dan** [comment]
> It looks like you are using an old config file. Use the .exe.config that comes with the release.

Thank for the advice. I found out the one of the script went wrong and mistake over written it with an old exe.config file.
