### ISSUE TITLE
Multi Instance support

### ISSUE THREAD

**Issue by MarcelDEV** [misterokaygo/MapAssist#54]
When I start my IsoBoxer instance from D2R, the overlay disappears. Is there a solution for this? 

Setup:
IsoBoxer Instance(InnerSpace) and normal Instance 

I start the first instance via the Battle.Net launcher and the second D2R instance via Innerspace (IsoBoxer).
As soon as the second instance is started, the D2RAssist overlay disappears.
When the second instance is started, no more requests are displayed in the D2MapApi CMD.

**Comment by Farmith** [comment]
Check my PR for a solution for this, goes for the "In focus" window (which ever one you are on) and displays the map on that window (as long as its a D2R client)

**Comment by sunkwolf** [comment]
> Check my PR for a solution for this, goes for the "In focus" window (which ever one you are on) and displays the map on that window (as long as its a D2R client)

could you please share how did fix it ?

**Comment by OneXDeveloper** [comment]
This is resolved on the develop branch. You can get the nightly release to test it out.
